name: cvcs
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - asttokens==2.4.0
      - backcall==0.2.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - cmake==3.27.5
      - contourpy==1.1.1
      - cycler==0.11.0
      - decorator==5.1.1
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - filelock==3.12.4
      - fonttools==4.42.1
      - grpcio==1.64.1
      - h5py==3.10.0
      - idna==3.4
      - imageio==2.34.2
      - importlib-metadata==8.0.0
      - importlib-resources==6.0.1
      - ipython==8.15.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - kornia==0.7.0
      - lazy-loader==0.4
      - lit==16.0.6
      - markdown==3.6
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.26.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - opencv-python==4.8.0.76
      - packaging==23.1
      - pandas==2.2.2
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - prompt-toolkit==3.0.39
      - protobuf==4.25.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2024.1
      - requests==2.31.0
      - scikit-image==0.24.0
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - six==1.16.0
      - stack-data==0.6.2
      - sympy==1.12
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tifffile==2024.7.2
      - torch==1.12.1+cu113
      - torchinfo==1.8.0
      - torchvision==0.13.1+cu113
      - tqdm==4.66.1
      - traitlets==5.10.0
      - triton==2.0.0
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - urllib3==2.0.6
      - wcwidth==0.2.6
      - werkzeug==3.0.3
      - zipp==3.17.0
prefix: /mnt/d/anaconda3/envs/cvcs
